name: Build Android 15 GKI Module
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的代码
        uses: actions/checkout@v4

      - name: 安装基础依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential flex git libelf-dev libssl-dev

      - name: 获取安卓官方 Clang 工具链
        run: |
          # 使用更稳定的 Android 官方存储库链接
          mkdir -p $GITHUB_WORKSPACE/clang-tools
          git clone https://googlesource.com $GITHUB_WORKSPACE/clang-tools --depth=1

      - name: 获取内核源码 (GKI 6.1)
        run: |
          # 拉取 Android 15 - 6.1 分支
          git clone https://googlesource.com $GITHUB_WORKSPACE/common --depth=1 -b android15-6.1

      - name: 编译模块
        run: |
          # 动态寻找 Clang 目录，防止版本号写死导致报错
          CLANG_DIR=$(ls -d $GITHUB_WORKSPACE/clang-tools/clang-r*)
          export PATH=$CLANG_DIR/bin:$PATH
          KDIR=$GITHUB_WORKSPACE/common
          
          # 1. 配置内核环境
          cd $KDIR
          make ARCH=arm64 LLVM=1 gki_defconfig
          make ARCH=arm64 LLVM=1 prepare modules_prepare

          # 2. 编译你的模块
          cd $GITHUB_WORKSPACE
          make ARCH=arm64 LLVM=1 CROSS_COMPILE=aarch64-linux-gnu- KDIR=$KDIR
          
      - name: 上传编译好的 KO 文件
        uses: actions/upload-artifact@v4
        with:
          name: hello-module
          path: ./*.ko
