name: Build Android ARM64 KO
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安装依赖
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential bison flex libssl-dev libelf-dev git

      # 预编译clang，不源码编译
      - name: Download Android Prebuilt Clang 17
        run: |
          wget https://dl.google.com/android/ndk/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip
          echo "PATH=$PWD/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      # 拉取内核源码
      - name: Pull Android Kernel Source
        run: |
          git clone --depth=1 --branch android14-6.1 https://android.googlesource.com/kernel/common kernel
          cd kernel
          # 直接复制仓库里本地的config，无任何网络URL
          cp ../device.config .config

      # 内核预处理
      - name: Prepare kernel
        run: |
          cd kernel
          export PATH=${{ env.PATH }}
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 olddefconfig
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 modules_prepare -j$(nproc)

      # 编译ko
      - name: Compile KO
        run: |
          export PATH=${{ env.PATH }}
          make -j$(nproc) KDIR=./kernel ARCH=arm64 LLVM=1

      # 上传产物
      - name: Upload Android KO
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-ko
          path: hello.ko
